version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "10:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
