# Generates a new CONTRIBUTIONS.md file and new github-metrics.svg.
name: Update Metrics and Contributions
on:
  # Schedule updates (every two weeks on Monday at 6am)
  schedule: [{cron: "0 6 */14 * 1"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-contribs-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Scopes: [pull-requests: read]
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "**/*.sum"

      - run: go test -race -shuffle=on -v ./...
        working-directory: ./gencontribs

      - run: go run .
        working-directory: ./gencontribs

      # Visit https://github.com/lowlighter/metrics#-documentation for full reference
      - uses: lowlighter/metrics@latest
        with:
          # A GitHub personal token is required since this action will fetch data that cannot be accessed through repository-scoped tokens.
          # Scopes: [public_repo, read:project, read:user]
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none

          # Options
          user: alexandear
          template: classic
          base: activity, repositories, metadata
          plugin_introduction_title: yes
          plugin_notable: no

      - run: sudo mv /metrics_renders/* ./

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update metrics and CONTRIBUTIONS"
          branch: main
          file_pattern: "github-metrics.svg CONTRIBUTIONS.md"
