name: Generate CONTRIBUTIONS
on:
  # Schedule updates (every two weeks on Monday at 6am)
  schedule: [{cron: "0 6 */14 * 1"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-contribs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Scopes: [pull-requests: read]
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "**/*.sum"

      - run: go test -race -shuffle=on -v ./...
        working-directory: ./gencontribs

      - run: go run .
        working-directory: ./gencontribs

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CONTRIBUTIONS"
          branch: main
          file_pattern: "CONTRIBUTIONS.md"
