# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day at 6am)
  schedule: [{cron: "0 6 * * 1"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Scopes: [pull-requests: read]
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.X'

      - run: go generate ./...
        working-directory: ./gencontribs

      - uses: lowlighter/metrics@latest
        with:
          # A GitHub personal token is required since this action will fetch data that cannot be accessed through repository-scoped tokens.
          # Scopes: [public_repo, read:project, read:user]
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none

          # Options
          user: alexandear
          template: classic
          base: activity, repositories, metadata
          plugin_introduction_title: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>10000 forks:>1000
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit

      - run: sudo mv /metrics_renders/* ./

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update metrics and CONTRIBUTIONS"
          branch: main
          file_pattern: "github-metrics.svg CONTRIBUTIONS.md"
