# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day at 6am)
  schedule: [{cron: "0 6 * * 1"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - run: go generate ./...

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none

          # Options
          user: alexandear
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit

      - run: sudo mv /metrics_renders/* ./

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update metrics and CONTRIBUTIONS"
          branch: main
          file_pattern: "github-metrics.svg CONTRIBUTIONS.md"
