# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every two weeks on Monday at 6am)
  schedule: [{cron: "0 6 */14 * 1"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          # A GitHub personal token is required since this action will fetch data that cannot be accessed through repository-scoped tokens.
          # Scopes: [public_repo, read:project, read:user]
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none

          # Options
          user: alexandear
          template: classic
          base: activity, repositories, metadata
          plugin_introduction_title: yes
          plugin_notable: no

      - run: sudo mv /metrics_renders/* ./

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update metrics"
          branch: main
          file_pattern: "github-metrics.svg"
